databases:
  - name: postgres
    ipAllowList: []
    databaseName: csie-casino
    user: csie-casino

services:
  - type: web
    name: csie-casino
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
